data <- read.table("household_power_consumption.txt",header=TRUE,sep=";")
subdata <- subset(data,data$Date %in% c('1/2/2007','2/2/2007'))
subdata$Date <- as.Date(subdata$Date,format='%d/%m/%Y')
subdata$Time <- strptime(subdata$Time, format = '%H:%M:%S')
png(filename='plot_3.png')
with(subdata,plot(Time,Sub_metering_1,type="n",xlab="",ylab="Energy sub metering"))
with(subdata,lines(Time,as.numeric(Sub_metering_1)))
with(subdata,lines(Time,as.numeric(Sub_metering_2),col="red"))
with(subdata,lines(Time,as.numeric(Sub_metering_3),col="blue"))
legend("topright", lty=1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()